modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "default_spawn_dimension"
version = "${version}"
displayName = "Default Spawn Dimension"
authors = "ACCBDD"
description = '''
A simple mod to change the default spawn dimension.
'''
#logoFile = ""

[[dependencies.default_spawn_dimension]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.default_spawn_dimension]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.default_spawn_dimension]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
